In [1]:
import numpy as np

In [2]:
arr = np.arange(11)

In [3]:
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [4]:
np.where(arr>5,arr*-1,arr)

array([  0,   1,   2,   3,   4,   5,  -6,  -7,  -8,  -9, -10])

Question 3

In [5]:
mat = np.array([['abc','A'],['def','B'],['ghi','C'],['jkl','D']])

In [6]:
arr = np.array(['abc','dfe','ghi','kjl']) 

In [7]:
mat

array([['abc', 'A'],
       ['def', 'B'],
       ['ghi', 'C'],
       ['jkl', 'D']], dtype='<U3')

In [8]:
arr

array(['abc', 'dfe', 'ghi', 'kjl'], dtype='<U3')

In [9]:
mat[mat[:,0] == arr][:,1]

array(['A', 'C'], dtype='<U3')

Solution for Q3 uses Fancy indexing

Question 4 Given a matrix mat, sort it by the second column.-----------------------------------------------

In [10]:
mat = np.array([[1,21,3],[5,4,2],[56,12,4]])

In [12]:
print(np.argsort(mat))

[[0 2 1]
 [2 1 0]
 [2 1 0]]


In [14]:
ind = np.argsort(mat[:1])
print(mat[ind])

[[[ 1 21  3]
  [56 12  4]
  [ 5  4  2]]]


Question 5:Given an array arr, find the top 4 maximum values. ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

In [15]:
arr = np.array([90, 14, 24, 13, 13, 590, 0, 45, 16, 50])

In [19]:
ind = np.argpartition(arr,4)[-4:]
arr[ind]

array([ 45,  50, 590,  90])

Question 6: Find the nearest number from the given number in an array +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

In [20]:
arr = np.array([10,55,22,3,6,44,9,54])
nearest_to = 50

In [23]:
arr[np.argmin(np.absolute(arr - 50))]

54