Question1: Given a matrix mat of size 3 x 3. Find all the even numbers situated in each of the row(s) whose end cumulative sum is greater than or equal to 150. ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

In [1]:
import numpy as np 

In [2]:
mat = np.array([[51,21,14], 
                [56,85,22], 
                [99,666,230]]).reshape(3,3)

In [3]:
print(np.cumsum(mat,axis=1))

[[ 51  72  86]
 [ 56 141 163]
 [ 99 765 995]]


In [4]:
arr1 = np.cumsum(mat,axis=1)[:,2]>150

In [5]:
print(arr1)

[False  True  True]


In [6]:
print(mat[arr1][mat[arr1]%2 == 0])

[ 56  22 666 230]


Question2: Given a matrix mat of size 3 x 3. Find the maximum numbers from each row, say N1, N2 and N3. Result in a matrix by adding:

N1 to the upper half elements of mat

N2 to the main diagonal elements of mat

N3 to the lower half elements of mat

In [7]:
mat = np.array([[10,5,9],
                [2,20,6],
                [8,3,30]]).reshape(3,3)

In [8]:
max1 = np.amax(mat,axis=1)

In [9]:
ind = np.tril_indices(3,-1)

In [10]:
print(mat)

[[10  5  9]
 [ 2 20  6]
 [ 8  3 30]]


In [11]:
upp_ind = np.mask_indices(3, np.triu)

In [13]:
mat[upp_ind] += max1[0]

In [14]:
print(mat)

[[30 25 29]
 [ 2 40 26]
 [ 8  3 50]]


In [15]:
mat[ind] += max1[2]

In [16]:
print(mat)

[[30 25 29]
 [32 40 26]
 [38 33 50]]
